[package]
name = "webrender_api"
version = "0.62.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
description = "Public API for WebRender"
edition = "2018"

[features]
# Note: nightly feature removed - serde/unstable causes compilation errors
# on stable Rust with serde_core 1.0.228+ (never_type feature gate)
nightly = ["euclid/unstable"]
serialize = []
deserialize = []
display_list_stats = []

[dependencies]
app_units = "0.7.3"
azul-core = { version = "0.0.6", path = "../../core" }
bitflags = { version = "2", default-features = false, features = ["serde"] }
byteorder = "1.2.1"
euclid = { version = "0.22.6", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["rc", "derive", "alloc"] }
serde_derive = "1.0"
serde_bytes = "0.11"
time = "0.3"
crossbeam-channel = "0.5"
