[package]
name = "azul-css"
version = "0.0.1"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MPL-2.0"
description = '''
    Common datatypes used for styling applications
    using the Azul desktop GUI framework
'''
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2021"
autoexamples = false

[dependencies]
libm = { version = "0.2.2", default-features = false }
azul-simplecss = { version = "0.1.1", default-features = false, optional = true }

[features]
parser = ["azul-simplecss"]