[package]
name = "azul-text-layout"
version = "0.0.5"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MPL-2.0"
description = '''
    Text layout algorithms Azul desktop GUI framework
'''
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "native" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2021"
readme = "./README.md"
autoexamples = false

[dependencies]
azul-css                = { path = "../azul-css", version = "0.0.1",   default-features = false }
azul-core               = { path = "../azul-core", version = "0.0.2", default-features = false, features = ["std"] }
unicode-normalization   = { version = "0.1.21",  default-features = false }
allsorts                = { version = "0.15.0", git = "https://github.com/fschutt/allsorts", branch = "optional-brotli", default-features = false, features = ["flate2_rust"] }
tinyvec                 = { version = "1.6.0", default-features = false }
ttf-parser              = { version = "0.15.2", default-features = false, features = ["variable-fonts"] }
