language: rust
script:
  - cargo build --all
  - cargo build --examples
  - cargo test --features "doc-test"

sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

# env:
#   global:
#   - RUSTFLAGS="-C link-dead-code"

# addons:
#   apt:
#     packages:
#       - libcurl4-openssl-dev
#       - libelf-dev
#       - libdw-dev
#       - cmake
#       - gcc
#       - binutils-dev
#       - libiberty-dev

# after_success: |
#   wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
#   tar xzf master.tar.gz &&
#   cd kcov-master &&
#   mkdir build &&
#   cd build &&
#   cmake .. &&
#   make &&
#   make install DESTDIR=../../kcov-build &&
#   cd ../.. &&
#   rm -rf kcov-master &&
#   for file in target/debug/azul-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
#   bash <(curl -s https://codecov.io/bash) &&
#   echo "Uploaded code coverage"