environment:
  global:
    PROJECT_NAME: azul
  matrix:
    # Disable windows-gnu because appveyor has problems installing CMAKE correctly
    # (CMAKE_C_COMPILER not set)
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    # This target is commented out because for some reason appveyor only ships
    # GCC in 32-bit mode, so when compiling miniz.c (require for zipping), it'll
    # fail although the build itself will work fine (because nobody uses a 32-bit
    # compiler anymore in the real world). Just use a 64-bit compiler and
    # everything will work fine.
    #
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

branches:
  only:
    - master

# Install Rust and Cargo
# Based on https://github.com/rust-lang/libc/blob/master/appveyor.yml
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\tools\mingw64\bin;C:\MinGW\bin;
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=% # ignore other MinGW shells, use C:\MinGW
  - gcc -v
  - rustc -vV
  - cargo -vV

# 'cargo test' takes care of building for us, so disable Appveyor's build stage.
# This prevents the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo check --verbose --examples
  - cargo check --no-default-features
  - cargo check --no-default-features --features="svg"
  - cargo check --no-default-features --features="logging"
  - cargo test --verbose --features "doc-test no-opengl-tests"
