[package]
name = "azul-examples-dynamic"
version = "0.0.1"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul GUI examples that dynamically link against libazul_dll.dylib
'''
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user-interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2021"
publish = false
build = "build.rs"

# No dependencies on azul crates - we link dynamically!
[dependencies]
# External dependencies if needed
# serde = { version = "1", optional = true }

[[example]]
name = "hello-world-dynamic"
path = "src/hello-world.rs"

[[example]]
name = "calc-dynamic"
path = "src/calc.rs"
