[package]
name = "webrender"
version = "0.62.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
description = "A GPU accelerated 2D renderer for web content"
build = "build.rs"
edition = "2018"

[features]
default = []
# All profiling, capture/replay, and display_list_stats features removed for minimal build

[build-dependencies]
webrender_build = { path = "../build" }

[dependencies]
bincode = "2.0"
bitflags = "2"
byteorder = "1.0"
euclid = "0.22.10"
fxhash = "0.2.1"
lazy_static = "1"
log = "0.4"
num-traits = "0.2"
plane-split = "0.18"
rayon = "1"
smallvec = "1.15.1"
time = "0.3"
api = { version = "0.62.0", path = "../api", package = "webrender_api" }
webrender_build = { path = "../build" }
glyph_rasterizer = { version = "0.1.0", path = "../glyph", package = "wr_azul_glyph_rasterizer", default-features = false }
azul-layout = { path = "../../layout" }
azul-core = { path = "../../core" }
azul-css = { path = "../../css" }
svg_fmt = "0.4"
derive_more = { version = "2.0", default-features = false, features = ["add_assign"] }
etagere = "0.2.13"
topological-sort = "0.2"
allocator-api2 = { version = "0.3.1", features = ["alloc"] }

[dev-dependencies]
mozangle = "0.5.3"
rand = "0.9"
