[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul GUI is a free, functional, immediate-mode GUI framework
    for rapid development of desktop applications written in Rust,
    supported by the Mozilla WebRender rendering engine
'''
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
readme = "../README.md"
exclude = ["../assets/*", "../doc/*", "../examples/*"]
autoexamples = false

[lib]
path = "../../azul/lib.rs"

[dependencies]
azul-css                = { version = "0.1.0",          default-features = false,                  path = "../azul-css"             }
azul-core               = { version = "0.1.0",          default-features = false,                  path = "../azul-core"            }
azul-layout             = { version = "0.1.0",          default-features = false,                  path = "../azul-layout"          }
gleam                   = { version = "0.6",            default-features = false                                                    }
glutin                  = { version = "0.22.0-alpha1",  default-features = false                                                    }
euclid                  = { version = "0.19.4",         default-features = false                                                    }
rusttype                = { version = "0.7.3",          default-features = false                                                    }
app_units               = { version = "0.7.1",          default-features = false                                                    }
unicode-normalization   = { version = "0.1.7",          default-features = false                                                    }
lazy_static             = { version = "1.2.0",          default-features = false                                                    }
tinyfiledialogs         = { version = "3.3.5",          default-features = false                                                    }
clipboard2              = { version = "0.1.1",          default-features = false                                                    }
font-loader             = { version = "0.8.0",          default-features = false                                                    }
xmlparser               = { version = "0.6.1",          default-features = false                                                    }
harfbuzz-sys            = { version = "0.3.0",          default-features = false                                                    }
azul-css-parser         = { version = "0.1.0",          default-features = false, optional = true, path = "../azul-css-parser"      }
azul-widgets            = { version = "0.1.0",          default-features = false, optional = true, path = "../azul-widgets"         }
azul-native-style       = { version = "0.1.0",          default-features = false, optional = true, path = "../azul-native-style"    }
serde_derive            = { version = "1",              default-features = false, optional = true                                   }
serde                   = { version = "1",              default-features = false, optional = true                                   }
log                     = { version = "0.4.6",          default-features = false, optional = true                                   }
stb_truetype            = { version = "0.2.2",          default-features = false, optional = true                                   }
fern                    = { version = "0.5.7",          default-features = false, optional = true                                   }
backtrace               = { version = "0.3.12",         default-features = false, optional = true, features = ["std", "libunwind", "libbacktrace", "coresymbolication", "dladdr", "dbghelp"] }
lyon                    = { version = "0.11.0",         default-features = false, optional = true                                   }
usvg                    = { version = "0.3.0",          default-features = false, optional = true                                   }
image                   = { version = "0.20.1",         default-features = false, optional = true, features = ["gif_codec", "jpeg", "png_codec", "tiff", "bmp"] }

# Linux: Use webrender with freetype feature enabled
[target.'cfg(target_os = "linux")'.dependencies]
webrender = { version = "0.58.0", default-features = false }
[target.'cfg(not(target_os = "linux"))'.dependencies]
webrender = { version = "0.58.0", default-features = false }

[features]
default = ["logging", "widgets", "native_style", "css_parser"]
# Enable this feature to enable crash logging & reporting.
# Azul will insert custom panic handlers to pop up a message and log
# crashes to an "error.log" file, see AppConfig for more details
logging = ["fern", "backtrace", "log"]
# For serializing / deserializing CSS colors using serde
serde_serialization = ["serde", "serde_derive"]
# Enable / diable the CSS parser
css_parser = ["azul-core/css_parser", "azul-css-parser"]
# Enable / disable the built-in widgets
widgets = ["azul-widgets"]
# Enable / disable the built-in SVG widgets (requires lyon - extra compilation time)
svg = ["widgets", "azul-widgets/svg"]
# Enable / disable the SVG parser (requires usvg)
svg_parsing = ["svg", "azul-widgets/svg_parsing"]
# Enable / disable the OS-native CSS style loader
native_style = ["azul-native-style"]
# On some applications you might not want to load any images. For these purposes
# the image crate can be disabled, to speed up compile times
image_loading = ["image"]
# Features to load extra image formats
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
jpeg_rayon = ["image/jpeg_rayon"]
dxt = ["image/dxt"]
webp = ["image/webp"]
pnm = ["image/pnm"]

## -----------

[[example]]
name = "async"
path = "../../examples/async/async.rs"
required-features = []

[[example]]
name = "calculator"
path = "../../examples/calculator/calculator.rs"
required-features = []

[[example]]
name = "game_of_life"
path = "../../examples/game_of_life/game_of_life.rs"
required-features = []

[[example]]
name = "hello_world"
path = "../../examples/hello_world/hello_world.rs"
required-features = []


[[example]]
name = "hot_reload"
path = "../../examples/hot_reload/hot_reload.rs"
required-features = ["image_loading"]

[[example]]
name = "list"
path = "../../examples/list/list.rs"
required-features = []

[[example]]
name = "opengl"
path = "../../examples/opengl/opengl.rs"
required-features = []

[[example]]
name = "slider"
path = "../../examples/slider/slider.rs"
required-features = []

[[example]]
name = "svg"
path = "../../examples/svg/svg.rs"
required-features = ["svg_parsing"]

[[example]]
name = "table"
path = "../../examples/table/table.rs"
required-features = []

[[example]]
name = "text_input"
path = "../../examples/text_input/text_input.rs"
required-features = []

[[example]]
name = "text_shaping"
path = "../../examples/text_shaping/text_shaping.rs"
required-features = []

[[example]]
name = "transparent_window"
path = "../../examples/transparent_window/transparent_window.rs"
required-features = []

[[example]]
name = "xml"
path = "../../examples/xml/xml.rs"
required-features = []
