[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul GUI is a free, functional, immediate-mode GUI framework
    for rapid development of desktop applications written in Rust,
    supported by the Mozilla WebRender rendering engine
'''
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
readme = "../README.md"
exclude = ["../assets/*", "../doc/*", "../examples/*"]
autoexamples = false
edition = "2018"

[lib]
path = "../../azul/src/lib.rs"

[dependencies]
azul-dll = { version = "0.1.0", path = "../azul-dll", default-features = false }

# [features]
# default = ["logging", "widgets", "native_style", "css_parser", "image_loading", "font_loading", "text_layout"]
# # Enable this feature to enable crash logging & reporting.
# # Azul will insert custom panic handlers to pop up a message and log
# # crashes to an "error.log" file, see AppConfig for more details
# logging = ["fern", "backtrace", "log"]
# # Enable / disable the built-in widgets
# widgets = ["azul-widgets"]
# # Enable / disable the OS-native CSS style loader
# native_style = ["azul-native-style"]
# # Enable / diable the CSS parser
# css_parser = ["azul-core/css_parser", "azul-css-parser"]
# # Enable / disable the built-in SVG widgets (requires lyon - extra compilation time)
# svg = ["widgets", "azul-widgets/svg"]
# # Enable / disable the SVG parser (requires usvg)
# svg_parsing = ["svg", "widgets", "azul-widgets/svg_parsing"]
# # Enable / disable the built-in SVG widgets (requires lyon - extra compilation time)
# svg_fonts = ["widgets", "azul-widgets/fonts"]
# # On some applications you might not want to load any images. For these purposes
# # the image crate can be disabled, to speed up compile times
# image_loading = ["azulc/image_loading"]
# # Enables loading of ICO files on the image decoder
# ico = ["azulc/ico"]
# # Enables loading of TGA files on the image decoder
# tga = ["azulc/tga"]
# # Enables loading of HDR files on the image decoder
# hdr = ["azulc/hdr"]
# # Enables parallel JPEG decoding on the image decoder
# jpeg_rayon = ["azulc/jpeg_rayon"]
# # Enables loading of DXT files on the image decoder
# dxt = ["azulc/dxt"]
# # Enables loading of WEBP files on the image decoder
# webp = ["azulc/webp"]
# # Enables loading of PNM files on the image decoder
# pnm = ["azulc/pnm"]
# # Activates the font-loading module, important to deactivate for example
# font_loading = ["azulc/font-loader"]
# # Text loading module, disable if you have a custom text layouting function
# text_layout = ["azulc/text_layout"]

## -----------

[[example]]
name = "async"
path = "../../examples/async/async.rs"
required-features = []

[[example]]
name = "calculator"
path = "../../examples/calculator/calculator.rs"
required-features = []

[[example]]
name = "game_of_life"
path = "../../examples/game_of_life/game_of_life.rs"
required-features = []

[[example]]
name = "hello_world"
path = "../../examples/hello_world/hello_world.rs"
required-features = []

[[example]]
name = "hot_reload"
path = "../../examples/hot_reload/hot_reload.rs"
required-features = ["image_loading"]

[[example]]
name = "list"
path = "../../examples/list/list.rs"
required-features = []

[[example]]
name = "opengl"
path = "../../examples/opengl/opengl.rs"
required-features = []

[[example]]
name = "slider"
path = "../../examples/slider/slider.rs"
required-features = []

[[example]]
name = "svg"
path = "../../examples/svg/svg.rs"
required-features = ["svg_parsing"]

[[example]]
name = "table"
path = "../../examples/table/table.rs"
required-features = []

[[example]]
name = "text_input"
path = "../../examples/text_input/text_input.rs"
required-features = []

[[example]]
name = "text_shaping"
path = "../../examples/text_shaping/text_shaping.rs"
required-features = []

[[example]]
name = "transparent_window"
path = "../../examples/transparent_window/transparent_window.rs"
required-features = []

[[example]]
name = "xml"
path = "../../examples/xml/xml.rs"
required-features = []

[[example]]
name = "headless"
path = "../../examples/headless/headless.rs"
required-features = []
