[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Sch√ºtt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul GUI is a free, functional, immediate-mode GUI framework
    for rapid development of desktop applications written in Rust,
    supported by the Mozilla WebRender rendering engine
'''
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
readme = "../README.md"
exclude = ["../assets/*", "../doc/*", "../examples/*"]
autoexamples = false

[lib]
path = "../../azul/lib.rs"

[dependencies]
azul-css                = { version = "0.1.0",                path = "../azul-css"                              }
azul-core               = { version = "0.1.0",                path = "../azul-core"                             }
azul-layout             = { version = "0.1.0",                path = "../azul-layout"                           }
azul-css-parser         = { version = "0.1.0",                path = "../azul-css-parser",      optional = true }
azul-widgets            = { version = "0.1.0",                path = "../azul-widgets",         optional = true }
azul-native-style       = { version = "0.1.0",                path = "../azul-native-style",    optional = true }
azul-dependencies       = { version = "0.1.0",                git = "https://github.com/maps4print/azul-dependencies", rev = "00e6e0ffacb008244d196df246db48f463a59992" }
serde_derive            = { version = "1",                    optional = true }
serde                   = { version = "1",                    optional = true }
gleam                   = { version = "0.6"                                                                     }

[features]
# The "SVG" feature only enables the creation of shapes / polygons, etc. not the actual parsing
# (which needs the `svg_parsing` feature).
default = [
    "logging",
    "widgets",
    "native_style",
    "css_parser",
]
# Enable this feature to enable crash logging & reporting.
# Azul will insert custom panic handlers to pop up a message and log
# crashes to an "error.log" file, see AppConfig for more details
logging = ["azul-dependencies/logging"]
# If you want an application icon, you can either load it via the raw
# RGBA bytes or use the icon_loading feature to decode it from a PNG / JPG /
# whatever image format on startup. Note that this will import the image
# dependency and use a bit of extra runtime.
icon_loading = ["azul-dependencies/icon_loading"]
# For serializing / deserializing CSS colors using serde
serde_serialization = ["azul-dependencies/serde_serialization", "azul-widgets/serde_serialization", "serde_derive", "serde"]
serde_serialization_css = ["azul-css-parser/serde_serialization", "serde_serialization"]
# On some applications you might not want to load any images. For these purposes
# the image crate can be disabled, to speed up compile times
image_loading = ["azul-dependencies/image_loading"]
# Features to load extra image formats
ico = ["azul-dependencies/ico"]
tga = ["azul-dependencies/tga"]
hdr = ["azul-dependencies/hdr"]
jpeg_rayon = ["azul-dependencies/jpeg_rayon"]
dxt = ["azul-dependencies/dxt"]
webp = ["azul-dependencies/webp"]
css_parser = ["azul-core/css_parser", "azul-css-parser"]
widgets = ["azul-widgets"]
native_style = ["azul-native-style"]
svg_parsing = ["azul-widgets/svg_parsing"]
svg = ["azul-widgets/svg"]

[[example]]
name = "async"
path = "../../examples/async/async.rs"
required-features = []

[[example]]
name = "calculator"
path = "../../examples/calculator/calculator.rs"
required-features = []

[[example]]
name = "game_of_life"
path = "../../examples/game_of_life/game_of_life.rs"
required-features = []

[[example]]
name = "hello_world"
path = "../../examples/hello_world/hello_world.rs"
required-features = []


[[example]]
name = "hot_reload"
path = "../../examples/hot_reload/hot_reload.rs"
required-features = ["image_loading"]

[[example]]
name = "list"
path = "../../examples/list/list.rs"
required-features = []

[[example]]
name = "opengl"
path = "../../examples/opengl/opengl.rs"
required-features = []

[[example]]
name = "slider"
path = "../../examples/slider/slider.rs"
required-features = []

[[example]]
name = "svg"
path = "../../examples/svg/svg.rs"
required-features = ["svg_parsing"]

[[example]]
name = "table"
path = "../../examples/table/table.rs"
required-features = []

# [[example]]
# name = "text_editor"
# path = "../../examples/text_editor/text_editor.rs"
# required-features = []

[[example]]
name = "text_input"
path = "../../examples/text_input/text_input.rs"
required-features = []

[[example]]
name = "text_shaping"
path = "../../examples/text_shaping/text_shaping.rs"
required-features = []

[[example]]
name = "transparent_window"
path = "../../examples/transparent_window/transparent_window.rs"
required-features = []

[[example]]
name = "xml"
path = "../../examples/xml/xml.rs"
required-features = []
