[package]
name = "peek-poke-derive"
version = "0.3.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
repository = "https://github.com/servo/webrender"
description = "Derive macro for peek-poke."
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
synstructure = "0.13"
unicode-xid = "0.2"
